apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: '{{ .Release.Name }}-{{ .Values.name }}'
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/Gin-G/argo-k8s-stuff
    chart: daskhub
    targetRevision: 2024.1.1
    helm:
    values: |
      {{- toYaml .Values.jupyterHubConfig | nindent 8 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: '{{ .Values.namespace }}'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
            